package template

import (
	"os"
	"os/exec"
	"regexp"
	"strings"
	"text/template"

	"github.com/okazaki-kk/ayaorm/template/templates"
)

func Generate(fileInspect FileInspect) error {
	filePath := strings.ToLower(fileInspect.StructInspect[0].ModelName) + "_gen.go"
	file, err := os.Create(filePath)
	if err != nil {
		return err
	}
	defer file.Close()

	var importText = `// Code generated by ayaorm. DO NOT EDIT.
	package main

	import (
		"fmt"

		"github.com/okazaki-kk/ayaorm"
	)
	`

	_, err = file.WriteString(importText)
	if err != nil {
		return err
	}

	for _, s := range fileInspect.StructInspect {
		s.PackageName = fileInspect.PackageName
		err := generateStruct(file, s)
		if err != nil {
			return err
		}
	}

	for _, f := range fileInspect.FuncInspect {
		err := generateFunc(file, f)
		if err != nil {
			return err
		}
	}

	err = exec.Command("go", "fmt", filePath).Run()
	if err != nil {
		return err
	}
	return nil
}

func generateStruct(file *os.File, structInspect StructInspect) error {
	funcMap := template.FuncMap{
		"toSnakeCase": toSnakeCase,
	}

	t, _ := template.New("Base").Funcs(funcMap).Parse(TextBody)

	_, err := t.New("Relation").Parse(templates.RelationTextBody)
	if err != nil {
		return err
	}
	_, err = t.New("Columns").Parse(templates.ColumnsTextBody)
	if err != nil {
		return err
	}
	_, err = t.New("CRUD").Parse(templates.CrudTextBody)
	if err != nil {
		return err
	}
	_, err = t.New("Search").Parse(templates.SearchTextBody)
	if err != nil {
		return err
	}
	_, err = t.New("Query").Parse(templates.QueryTextBody)
	if err != nil {
		return err
	}

	err = t.Execute(file, structInspect)
	if err != nil {
		return err
	}
	return nil
}

func generateFunc(file *os.File, funcInspect FuncInspect) error {
	funcMap := template.FuncMap{
		"toSnakeCase": toSnakeCase,
	}

	t, _ := template.New("Base").Funcs(funcMap).Parse(FuncBody)

	_, err := t.New("Joins").Parse(templates.JoinsTextBody)
	if err != nil {
		return err
	}

	err = t.Execute(file, funcInspect)
	if err != nil {
		return err
	}
	return nil
}

func GenerateDB() error {
	f, err := os.Create("db_gen.go")
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.Write([]byte(dbTextBody))
	if err != nil {
		return err
	}
	err = exec.Command("go", "fmt", "db_gen.go").Run()
	if err != nil {
		return err
	}
	return nil
}

func toSnakeCase(s string) string {
	const snake = "${1}_${2}"
	reg1 := regexp.MustCompile("([A-Z]+)([A-Z][a-z])")
	reg2 := regexp.MustCompile("([a-z])([A-Z])")
	return strings.ToLower(reg2.ReplaceAllString(reg1.ReplaceAllString(s, snake), snake))
}
