package template

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"text/template"

	"github.com/okazaki-kk/ayaorm"
	"github.com/okazaki-kk/ayaorm/template/templates"
)

func Generate(from string, fileInspect FileInspect) error {
	filePath := strings.Split(from, ".go")[0] + "_gen.go"
	file, err := os.Create(filePath)
	if err != nil {
		return err
	}
	defer file.Close()

	file.WriteString("// Code generated by ayaorm. DO NOT EDIT.\n")
	file.WriteString(fmt.Sprintf("package %s\n\n", fileInspect.PackageName))

	var importText = `
	import (
		"fmt"

		"github.com/okazaki-kk/ayaorm"
	)
	`

	_, err = file.WriteString(importText)
	if err != nil {
		return err
	}

	for _, s := range fileInspect.StructInspect {
		s.PackageName = fileInspect.PackageName
		err := generateStruct(file, s)
		if err != nil {
			return err
		}
	}

	for _, f := range fileInspect.FuncInspect {
		var err error
		if f.BelongTo {
			err = generateBelongsToFunc(file, f)
		} else if f.HasMany {
			err = generateHasManyFunc(file, f)
		}
		if err != nil {
			return err
		}
	}

	err = exec.Command("go", "fmt", filePath).Run()
	if err != nil {
		return err
	}

	err = generateDB(fileInspect.PackageName)
	if err != nil {
		return err
	}

	return nil
}

func generateStruct(file *os.File, structInspect StructInspect) error {
	funcMap := template.FuncMap{
		"toSnakeCase": ayaorm.ToSnakeCase,
	}

	t, _ := template.New("Base").Funcs(funcMap).Parse(TextBody)

	_, err := t.New("Relation").Parse(templates.RelationTextBody)
	if err != nil {
		return err
	}
	_, err = t.New("Columns").Parse(templates.ColumnsTextBody)
	if err != nil {
		return err
	}
	_, err = t.New("CRUD").Parse(templates.CrudTextBody)
	if err != nil {
		return err
	}
	_, err = t.New("Search").Parse(templates.SearchTextBody)
	if err != nil {
		return err
	}
	_, err = t.New("Query").Parse(templates.QueryTextBody)
	if err != nil {
		return err
	}

	err = t.Execute(file, structInspect)
	if err != nil {
		return err
	}
	return nil
}

func generateHasManyFunc(file *os.File, funcInspect FuncInspect) error {
	funcMap := template.FuncMap{
		"toSnakeCase": ayaorm.ToSnakeCase,
	}

	t, _ := template.New("Base").Funcs(funcMap).Parse(FuncBody)

	_, err := t.New("Joins").Parse(templates.HasManyTextBody)
	if err != nil {
		return err
	}

	err = t.Execute(file, funcInspect)
	if err != nil {
		return err
	}
	return nil
}

func generateBelongsToFunc(file *os.File, funcInspect FuncInspect) error {
	funcMap := template.FuncMap{
		"toSnakeCase": ayaorm.ToSnakeCase,
	}

	t, _ := template.New("Base").Funcs(funcMap).Parse(FuncBody)

	_, err := t.New("Joins").Parse(templates.BelongsTextBody)
	if err != nil {
		return err
	}

	err = t.Execute(file, funcInspect)
	if err != nil {
		return err
	}
	return nil
}

func generateDB(packageName string) error {
	f, err := os.Create("db_gen.go")
	if err != nil {
		return err
	}
	defer f.Close()

	f.WriteString("// Code generated by ayaorm. DO NOT EDIT.\n")
	f.WriteString(fmt.Sprint("package ", packageName, "\n\n"))
	_, err = f.Write([]byte(dbTextBody))
	if err != nil {
		return err
	}
	err = exec.Command("go", "fmt", "db_gen.go").Run()
	if err != nil {
		return err
	}
	return nil
}
