package template

var textBody = `
		{{define "Base"}}
		{{ template "Package" . }}

		{{ template "Import" . }}

		{{ template "Relation" . }}

		{{ template "CRUD" . }}

		{{ template "Search" . }}

		{{ template "Query" . }}

		{{ template "Columns" . }}
		{{end}}
	`

var dbTextBody = `
		// Code generated by ayaorm. DO NOT EDIT.
		package main

		import "database/sql"

		var db *sql.DB
`
