name: golangci-lint
on:
  push:
    branches:
      - develop
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:

  check:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: todo
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: set MySQL sql_mode
      run: |
        mysql --protocol=tcp --password=${MYSQL_PASSWORD} -u root mysql <<SQL
        SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';
        SET GLOBAL character_set_server = 'utf8mb4';
        SET GLOBAL collation_server = 'utf8mb4_general_ci';
        SQL

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod
        cache: true
    - run: go mod download


    - name: Build
      run: go build .

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        tool_name: errcheck
        level: info

    - name: Test
      run: make test
