name: golangci-lint
on:
  push:
    branches:
      - develop
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:

  check:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: todo
          MYSQL_USER: root
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod
        cache: true
    - run: go mod download


    - name: Build
      run: go build .

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        tool_name: errcheck
        level: info

    - name: Test
      run: make test
